/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        nord0: '#2e3440',
        nord1: '#3b4252',
        nord2: '#434c5e',
        nord3: '#4c566a',
        nord4: '#d8dee9',
        nord5: '#e5e9f0',
        nord6: '#eceff4',
        nord7: '#8fbcbb',
        nord8: '#88c0d0',
        nord9: '#81a1c1',
        nord10: '#5e81ac',
        nord11: '#bf616a',
        nord12: '#d08770',
        nord13: '#ebcb8b',
        nord14: '#a3be8c',
        nord15: '#b48ead',
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'bg-elevated': 'var(--bg-elevated)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-muted': 'var(--accent-muted)',
        border: 'var(--border)',
        error: 'var(--error)',
        warning: 'var(--warning)',
        success: 'var(--success)',
      },
      animation: {
        'page-bounce': 'page-bounce 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'placeholder-appear': 'placeholder-appear 0.15s ease-out',
        'widget-bounce': 'widget-bounce 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        'page-bounce': {
          '0%': { transform: 'scale(0.9) translateY(-5px)', opacity: '0.8' },
          '50%': { transform: 'scale(1.05) translateY(2px)' },
          '75%': { transform: 'scale(0.98) translateY(-1px)' },
          '100%': { transform: 'scale(1) translateY(0)', opacity: '1' },
        },
        'placeholder-appear': {
          '0%': { transform: 'scaleY(0)', opacity: '0' },
          '100%': { transform: 'scaleY(1)', opacity: '1' },
        },
        'widget-bounce': {
          '0%': { transform: 'scale(0.9) translateY(-10px)', opacity: '0.8' },
          '50%': { transform: 'scale(1.02) translateY(2px)' },
          '75%': { transform: 'scale(0.99) translateY(-1px)' },
          '100%': { transform: 'scale(1) translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
